[package]
name = "mathsbot"
version = "0.1.0"
authors = ["Jamie McClymont <jamie.mcclymont@gmail.com>"]

[dependencies]
serenity = "0.4"
tempdir = "0.3"
regex = "0.2"
lazy_static = "0.2"
libc = "0.2"
log = "0.3"
env_logger = "0.4"
typemap = "0.3"
